---
- name: Deploy Docker Image on Azure VM
  hosts: azure_vms
  become: true
  vars:
    docker_image_tar: "automated_app.tar"  # Local path to the tar file
    image_name: "automated_app"  # Name for the image to be used in the container
    container_name: "my_automation"  # Name for the running container
    docker_image_tar_dest: "/home/azureadmin/automated_app.tar"  # Path on the Azure VM where the tar file will be copied

  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Upload Docker image tar file to VM
      copy:
        src: "{{ docker_image_tar }}"
        dest: "{{ docker_image_tar_dest }}"
        mode: '0644'

    - name: Load Docker image from tar file
      command: "docker load -i /home/azureadmin/automated_app.tar"
      args:
        creates: "/var/lib/docker/images/{{ image_name }}.tar"

    - name: Run Docker container from the loaded image
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        restart_policy: always
        ports:
          - "80:80"  # Example port mapping, adjust as needed

    - name: Clean up the uploaded tar file
      file:
        path: "{{ docker_image_tar_dest }}"
        state: absent
