name: CI CD Automatic Deployment
on: 
  push: 
    branches:
      main
jobs:
  terraform-deploy:
    runs-on: devops

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Update apt and install prerequisites
        run: |
          sudo apt update -y || true
          sudo apt upgrade -y || true
          
          sudo apt install -y ansible
          echo "############# Ansible Version #############"
          ansible --version
          echo "############# Ansible Version #############"
          
          sudo apt-get install -y powershell
          echo "############# Powershell Version #############"
          pwsh --version
          echo "############# Powershell Version #############"
          
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash || true
          echo "############# AZ Version #############"
          az --version
          echo "############# AZ Version #############"
          sudo apt install -y docker.io
          sudo service docker start
          sudo service docker status || true
          echo "############# Docker Version #############"
          docker --version
          echo "############# Docker Version #############"

      - name: Deploy Docker Image to Infrastructure
        shell: pwsh
        run: |
          $vm_ips = az vm list-ip-addresses --query "[].virtualMachine.network.publicIpAddresses[].ipAddress" -o tsv
          Set-Location Install_App_VM_Ansible
          Set-Location ..
          Set-Location HelloWorld
          docker build -t automated_app .
          Set-Location ..
          Set-Location Install_App_VM_Ansible
          docker save -o automated_app.tar automated_app
          foreach ($ip in $vm_ips)
          {
              $hostsContent = @"
          [azure_vm]
          azure_vms ansible_host=$ip ansible_user=${{ secrets.AZURE_USER }}
          "@
              $hostsFilePath = "hosts.ini"
              $hostsContent | Out-File -FilePath $hostsFilePath -Encoding UTF8
              Write-Host "hosts.ini file has been created at $hostsFilePath"
              ansible-playbook -i hosts.ini "./deploy_docker_image.yml" -e ansible_password=${{ secrets.MY_PASSWORD }}
          }

          
